name: Weekly GitHub KPI Report

on:
  schedule:
    - cron: '0 17 * * 5'  # Every Friday at 17:00 UTC
  workflow_dispatch:      # Allow manual run from GitHub UI

jobs:
  generate-kpi-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run KPI report generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py

      - name: Commit and push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/
          git commit -m "📊 Weekly KPI Report (automated)"
          git push
